# Generated by Django 4.2.9 on 2024-05-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_company_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiarysector', to='home.sector'),
        ),
    ]
